### ISSUE TITLE
Reader is not working on the site https://gamma.app 

### ISSUE THREAD

**Issue by almakedon** [jina-ai/reader#101]
Use this Url as example 
https://r.jina.ai/https://gamma.app/docs/Dirt-Control-for-Car-Manufacturing-Paint-Shop-b8wserfhbrq0pu6?mode=doc

It returns :
Title: Gamma

URL Source: https://gamma.app/docs/Dirt-Control-for-Car-Manufacturing-Paint-Shop-b8wserfhbrq0pu6?mode=doc

Markdown Content:
Gamma
===============

Thank you guys!

**Comment by nomagick** [comment]
This site specifically blocks bots like Reader.
There's nothing we can do about it.
