### ISSUE TITLE
Why did I get an English version when I crawled a Chinese website?

### ISSUE THREAD

**Issue by 1linS** [jina-ai/reader#102]
Why did I get an English version when I crawled a Chinese website?
example：https://support.zoom.com/hc/zh/article?id=zm_kb&sysparm_article=KB0062485#collapseAndroid
The webpage displays in Chinese, but the crawling result is in the English version

**Comment by hanxiao** [comment]
my gut feeling is our Reader's "browser locale" is set to English by default but the webpage u showed there is implemented in a way that during `pageOnLoad` it overrides the language according to the browser locale despite ur URL has specified chinese `/hc/zh`


plz give it check @nomagick if this is the case, we should have a Locale exposed as a parameter for reader?

**Comment by mapleeit** [comment]
Hi @1linS 

The webage doesn't respect the language setting in the url. Instead, it uses language setting of the browser. I'm exposing the parameter to give user freedom. I'll let you know how to use it once the implementation is done.

**Comment by mapleeit** [comment]
By enabling `Browser Locale` config and setting the value to `zh-CN`, you can get the Chinese content. 

<img width="715" alt="Screenshot 2024-08-20 at 16 29 39" src="https://github.com/user-attachments/assets/686dca46-22db-4a0d-a950-4bd911634fbc">

I'm closing the issue now, feel free to reopen and let me know if there is still something wrong.
