### ISSUE TITLE
Feature Request: Ability to Remove Specific Elements

### ISSUE THREAD

**Issue by beiyanpiki** [jina-ai/reader#103]
Thank you for providing these fantastic tools!

Currently, users can extract specific parts of a document by setting the `X-Target-Selector`. However, it would be highly beneficial if the tool could also remove specific elements or tags such as `<nav>`, `<footer>`, etc. Sometimes these elements are frequently irrelevant for content parsing and could enhance the accuracy and relevance of the extracted data.

Is it possible to implement a feature that allows users to specify elements or tags to be excluded from the extraction process?

**Comment by njgage** [comment]
Absolutely second that - often ~25% of the text content is coming from nav, header & footer content etc and it would be great to exclude these common elements.

**Comment by nomagick** [comment]
That would be `x-remove-selector` though not yet documented on Jina AI website

```
curl https://r.jina.ai/www.google.com -H 'x-remove-selector: a'
```
