### ISSUE TITLE
Jina reader to read pdf files from google drive / run it on local files ?

### ISSUE THREAD

**Issue by timtensor** [jina-ai/reader#104]
Hi , i think it is not possible to run jina reader on pdf files uploaded on the google drive as you need absolute path to the pdf. Is there a way to also make it possible to run with google drive. 

Also another question , is it possible or is there a way to run the jina reader on offline pdf files.

**Comment by timtensor** [comment]
@mapleeit yes that would be extremely helpful . If I understand with the api end point from jina reader we could actually parse pdfs locally without the need to upload it to cloud. 

Thanks a lot for your explanation.

**Comment by timtensor** [comment]
@mapleeit i tried to run reader api , for the following pdf link . It seems to return not the compelte text. Is there a reason for it ? 
[link](https://lazy-investing.com/wp-content/uploads/2024/08/56068_HRA2563_DVO_R_2023-04-18_12739485_94160.pdf)

**Comment by mapleeit** [comment]
> @mapleeit yes that would be extremely helpful . If I understand with the api end point from jina reader we could actually parse pdfs locally without the need to upload it to cloud.
> 
> Thanks a lot for your explanation.

@timtensor the first 2 pages are from scanned copy instead of pure image, which is not supported in our parser.

**Comment by mapleeit** [comment]
> Do you think if that satisfies your need if we provide an API endpoint that supports you to upload your local pdf?

The API is ready, here is the usage example: 

- you can type whatever link in the `url` field
- for `pdf` field, please pass the base64 encoded string of the pdf file. 

```bash
curl --location 'https://r.jina.ai/' \
--header 'Content-Type: application/json' \
--data '{
    "url": "https://example.com/",    
    "pdf": "JVBERi0xLjcKCjEgMCBvYmogICUgZW50cnkgcG9pbnQKPDwKICAvVHlwZSAvQ2F0YWxvZwogIC9QYWdlcyAyIDAgUgo+PgplbmRvYmoKCjIgMCBvYmoKPDwKICAvVHlwZSAvUGFnZXMKICAvTWVkaWFCb3ggWyAwIDAgMjAwIDIwMCBdCiAgL0NvdW50IDEKICAvS2lkcyBbIDMgMCBSIF0KPj4KZW5kb2JqCgozIDAgb2JqCjw8CiAgL1R5cGUgL1BhZ2UKICAvUGFyZW50IDIgMCBSCiAgL1Jlc291cmNlcyA8PAogICAgL0ZvbnQgPDwKICAgICAgL0YxIDQgMCBSIAogICAgPj4KICA+PgogIC9Db250ZW50cyA1IDAgUgo+PgplbmRvYmoKCjQgMCBvYmoKPDwKICAvVHlwZSAvRm9udAogIC9TdWJ0eXBlIC9UeXBlMQogIC9CYXNlRm9udCAvVGltZXMtUm9tYW4KPj4KZW5kb2JqCgo1IDAgb2JqICAlIHBhZ2UgY29udGVudAo8PAogIC9MZW5ndGggNDQKPj4Kc3RyZWFtCkJUCjcwIDUwIFRECi9GMSAxMiBUZgooSGVsbG8sIHdvcmxkISkgVGoKRVQKZW5kc3RyZWFtCmVuZG9iagoKeHJlZgowIDYKMDAwMDAwMDAwMCA2NTUzNSBmIAowMDAwMDAwMDEwIDAwMDAwIG4gCjAwMDAwMDAwNzkgMDAwMDAgbiAKMDAwMDAwMDE3MyAwMDAwMCBuIAowMDAwMDAwMzAxIDAwMDAwIG4gCjAwMDAwMDAzODAgMDAwMDAgbiAKdHJhaWxlcgo8PAogIC9TaXplIDYKICAvUm9vdCAxIDAgUgo+PgpzdGFydHhyZWYKNDkyCiUlRU9G"
}'
```

**Comment by pmahan00** [comment]
@mapleeit one quick question . Is it also possible to run on internal links ? For running it on local hosted websites for example ?  like after concating with internal websites?
