### ISSUE TITLE
ResearchGate PDF links return empty content for most times

### ISSUE THREAD

**Issue by phunterlau** [jina-ai/reader#106]
It would be very helpful if research gate's PDF can be accessed by Reader API. Thank you.
 
Example links

Research gate: https://www.researchgate.net/profile/Luca-Mertens-2/publication/382994225_Model-Based_Reinforcement_Learning_Approaches_in_the_Low-Data-Regime/links/66b6284e51aa0775f2779ac0/Model-Based-Reinforcement-Learning-Approaches-in-the-Low-Data-Regime.pdf

**Comment by phunterlau** [comment]
The same with IEEE free PDFs like https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9275593 Thanks.

**Comment by mapleeit** [comment]
Hi @phunterlau 

[The url from research gate ](https://www.researchgate.net/profile/Luca-Mertens-2/publication/382994225_Model-Based_Reinforcement_Learning_Approaches_in_the_Low-Data-Regime/links/66b6284e51aa0775f2779ac0/Model-Based-Reinforcement-Learning-Approaches-in-the-Low-Data-Regime.pdf)works for me, what's the result on your side? 


For https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9275593, you can use `POST mode`. Screenshot shown below. 

<img width="1519" alt="Screenshot 2024-08-19 at 16 24 40" src="https://github.com/user-attachments/assets/a602b875-df0d-47da-960f-2d8ec3acfa5f">

**Comment by mapleeit** [comment]
One suggestion, for this webpage https://www.researchgate.net/publication/382994225_Model-Based_Reinforcement_Learning_Approaches_in_the_Low-Data-Regime

If you only want the pdf content, you can enable the `Target Selector` option, and set value as `#pdf-html-reader` to avoid the ads and other meaningless content.

<img width="499" alt="Screenshot 2024-08-19 at 17 28 18" src="https://github.com/user-attachments/assets/624bbb8b-875b-44ef-a276-34083f0225b8">

**Comment by phunterlau** [comment]
> Hi @phunterlau
> 
> [The url from research gate ](https://www.researchgate.net/profile/Luca-Mertens-2/publication/382994225_Model-Based_Reinforcement_Learning_Approaches_in_the_Low-Data-Regime/links/66b6284e51aa0775f2779ac0/Model-Based-Reinforcement-Learning-Approaches-in-the-Low-Data-Regime.pdf)works for me, what's the result on your side?
> 
> For https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9275593, you can use `POST mode`. Screenshot shown below.
> 
> <img alt="Screenshot 2024-08-19 at 16 24 40" width="1519" src="https://private-user-images.githubusercontent.com/4194287/359034463-a602b875-df0d-47da-960f-2d8ec3acfa5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMDI1MzIsIm5iZiI6MTcyNDEwMjIzMiwicGF0aCI6Ii80MTk0Mjg3LzM1OTAzNDQ2My1hNjAyYjg3NS1kZjBkLTQ3ZGEtOTYwZi0yZDhlYzNhY2ZhNWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTlUMjExNzEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGNlZGIwYjUzNWU0MTIyZjZlZTZmYTBkNmRjM2EwNDUzMDY1YTU1N2U4YWUyMzE2ZWEzNGNjM2UxNGU5MzY4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.v8ykPx4WUAmnYopbP73bM0Oz75dV6nSgYj4wfk14Tsg">

Big thanks. The researchgate link shows either empty content or "verify you are a human" content.

**Comment by phunterlau** [comment]
Thanks. Do we support any parameters to pass refer links to reader? Some URLs check its source of refer like the following. If we remove `-e` the site returns error page

```
curl -L -e "https://scholar.google.com/" \
"https://www.academia.edu/download/51627580/A_Generalized_Reinforcement-Learning_Mod20170203-31871-44ae37.pdf?hl=en&sa=T&oi=ggp&ct=res&cd=13&d=7556059458401941712&ei=IcXCZpzRGPCz6rQP5oSLmQM" \
-H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" \
-o "A_Generalized_Reinforcement-Learning_Model.pdf"
```

**Comment by mapleeit** [comment]
It's supported now. 

You can either pass `referer` in POST request body

```
curl --location 'https://r.jina.ai' \
--header 'Content-Type: application/json' \
--data '{
    "url": "https://www.academia.edu/download/51627580/A_Generalized_Reinforcement-Learning_Mod20170203-31871-44ae37.pdf?hl=en&sa=T&oi=ggp&ct=res&cd=13&d=7556059458401941712&ei=IcXCZpzRGPCz6rQP5oSLmQM",
    "referer": "https://scholar.google.com/",
    "noCache": true
}'
```

or pass it in the GET request header

```
curl --location 'https://r.jina.ai/https://www.academia.edu/download/51627580/A_Generalized_Reinforcement-Learning_Mod20170203-31871-44ae37.pdf?hl=en&sa=T&oi=ggp&ct=res&cd=13&d=7556059458401941712&ei=IcXCZpzRGPCz6rQP5oSLmQM' \
--header 'X-Referer: https://scholar.google.com' \
--header 'X-No-Cache: true'
```
