### ISSUE TITLE
Reader API gets blocked on Amazon links

### ISSUE THREAD

**Issue by pi-or-die** [jina-ai/reader#108]
Using the Reader API on Amazon links (only tested for US) returns captcha content, showing that Amazon is detecting the Reader as a bot. 

Example call: https://r.jina.ai/https://www.amazon.com/ANGRY-ORANGE-Gallon-Refill-Ready/dp/B08WLZ1NT6/?content-id=amzn1.sym.255b3518-6e7f-495c-8611-30a58648072e:amzn1.symc.a68f4ca3-28dc-4388-a2cf-24672c480d8f

Response:
#### Enter the characters you see below

Sorry, we just need to make sure you're not a robot. For best results, please make sure your browser is accepting cookies.

#### Type the characters you see in this image:

![Image 1](https://images-na.ssl-images-amazon.com/captcha/perumqgc/Captcha_aavhwvsjgl.jpg)

Try different image

[Conditions of Use](https://www.amazon.com/gp/help/customer/display.html/ref=footer_cou?ie=UTF8&nodeId=508088) [Privacy Policy](https://www.amazon.com/gp/help/customer/display.html/ref=footer_privacy?ie=UTF8&nodeId=468496)

© 1996-2014, Amazon.com, Inc. or its affiliates ![Image 2](https://fls-na.amazon.com/1/oc-csi/1/OP/requestId=XEC50ZXMM1DCCA1C79NN&js=1)

**Comment by nomagick** [comment]
Reader does not hack CAPTCHA protections of other websites. 
As this is probably a violation of their ToS.

**Comment by VBS2004** [comment]
@norvalbv did u get a solution for it? I am facing similar fate
