### ISSUE TITLE
您好，您这个项目我觉得非常有用，请问您是用的LLM来做的处理吗？

### ISSUE THREAD

**Issue by annian101** [jina-ai/reader#11]
您好，您这个项目我觉得非常有用，请问您是用的LLM来做的处理吗？

**Comment by hanxiao** [comment]
基本面上不是，今天刚引入了一些VLM做图片标注，所以是一点但也不是。

**Comment by h2s1652** [comment]
> @hanxiao @annian101 I build a same tool a week ago, you could try it with https://pagereader.aicanvas.app/

Is this project open source?

**Comment by iflamed** [comment]
> > @hanxiao @annian101 I build a same tool a week ago, you could try it with https://pagereader.aicanvas.app/
> 
> Is this project open source?

@h2s1652 It's not currently open-sourced, and after seeing jina open-sourced, I probably won't consider open-sourcing it either.

**Comment by annian101** [comment]
> 基本面上不是，今天刚引入了一些VLM做图片标注，所以是一点但也不是。

哦哦，因为我最近想做一个通用的爬虫模型，但是在页面处理上我是用html2text处理的，然后用LLM进行分析，但是效果很不尽如人意。所以我对您这个项目非常感兴趣
