### ISSUE TITLE
Reader can't read PDFs that are automatically downloaded?

### ISSUE THREAD

**Issue by oscar-o-oneill** [jina-ai/reader#114]
Hi there. I would like to use Reader for extracting content from PDFs. And it works great for PDFs that open directly in the browser, but sometimes those PDFs don't display directly in the browser, and are instead downloaded.

Like this URL: https://dalspace.library.dal.ca/bitstream/handle/10222/84361/AliMacKellar2024.pdf?sequence=1&isAllowed=y

I get this result from the HTTP request:
`{"data":null,"cause":{},"code":422,"name":"AssertionFailureError","status":42206,"message":"Failed to goto https://dalspace.library.dal.ca/bitstream/handle/10222/84361/AliMacKellar2024.pdf?sequence=1&isAllowed=y: Error: net::ERR_ABORTED at https://dalspace.library.dal.ca/bitstream/handle/10222/84361/AliMacKellar2024.pdf?sequence=1&isAllowed=y","readableMessage":"AssertionFailureError: Failed to goto https://dalspace.library.dal.ca/bitstream/handle/10222/84361/AliMacKellar2024.pdf?sequence=1&isAllowed=y: Error: net::ERR_ABORTED at https://dalspace.library.dal.ca/bitstream/handle/10222/84361/AliMacKellar2024.pdf?sequence=1&isAllowed=y"}`

Will there ever be functionality to handle these kinds of PDFs that automatically download?

Thank you.

**Comment by oscar-o-oneill** [comment]
Here's another one that failed in the same way.

https://harvest.usask.ca/bitstream/10388/13386/1/ALHASSAN-DISSERTATION-2021.pdf

`{"data":null,"cause":{},"code":422,"name":"AssertionFailureError","status":42206,"message":"Failed to goto https://harvest.usask.ca/bitstream/10388/13386/1/ALHASSAN-DISSERTATION-2021.pdf: Error: net::ERR_ABORTED at https://harvest.usask.ca/bitstream/10388/13386/1/ALHASSAN-DISSERTATION-2021.pdf","readableMessage":"AssertionFailureError: Failed to goto https://harvest.usask.ca/bitstream/10388/13386/1/ALHASSAN-DISSERTATION-2021.pdf: Error: net::ERR_ABORTED at https://harvest.usask.ca/bitstream/10388/13386/1/ALHASSAN-DISSERTATION-2021.pdf"}`

**Comment by nomagick** [comment]
Thanks for reporting this to us btw.

**Comment by oscar-o-oneill** [comment]
Hi @nomagick, awesome, thank you for fixing it! I can confirm that the two links ([1](https://r.jina.ai/https://dalspace.library.dal.ca/bitstream/handle/10222/84361/AliMacKellar2024.pdf?sequence=1&isAllowed=y)) ([2](https://r.jina.ai/https://harvest.usask.ca/bitstream/10388/13386/1/ALHASSAN-DISSERTATION-2021.pdf)) that previously failed now work great.

Thanks again. And I will be sure to report any more issues that I encounter with Reader, as I'm using it to process thousands of public PDF documents.
