### ISSUE TITLE
bug: incorrect attribute name for URL

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/reader#116]
There are three dots where the URL attribute name should be.

Go on https://jina.ai/reader/ and run a sample request with search activated and json response.
<img width="777" alt="image" src="https://github.com/user-attachments/assets/1d7a415e-01da-4f78-a262-7ce0a4dfa5ce">

**Comment by florian-hoenicke** [comment]
must be just a display issue since the curl request works for me

**Comment by hanxiao** [comment]
@shazhou2015

**Comment by shazhou2015** [comment]
I saw that @nomagick had already fixed it last week.
