### ISSUE TITLE
Error when scraping fashion websites for research

### ISSUE THREAD

**Issue by Jaunson** [jina-ai/reader#117]
I keep getting this error when scrapping some fashion websites for a larger research project:

{"code":9,"status":50000,"message":"9 FAILED_PRECONDITION: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/reader-6b7dc/firestore/indexes?create_composite=Ckxwcm9qZWN0cy9yZWFkZXItNmI3ZGMvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL2FwaVJvbGwvaW5kZXhlcy9fEAEaCAoEdGFncxgBGgoKBnN0YXR1cxABGgcKA3VpZBABGg0KCWNyZWF0ZWRBdBABGgwKCF9fbmFtZV9fEAE","details":"The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/reader-6b7dc/firestore/indexes?create_composite=Ckxwcm9qZWN0cy9yZWFkZXItNmI3ZGMvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL2FwaVJvbGwvaW5kZXhlcy9fEAEaCAoEdGFncxgBGgoKBnN0YXR1cxABGgcKA3VpZBABGg0KCWNyZWF0ZWRBdBABGgwKCF9fbmFtZV9fEAE","metadata":{"x-debug-tracking-id":["10277779323004301572;o=1"]},"name":"Error"}

Websites:

{'Tory Burch': 'https://www.toryburch.com/',
 'Tribe Of Two': 'https://www.tribeoftwo.com/',
 'Tura Eyewear': 'https://www.tura.com/',
 'Two Blind Brothers': 'https://twoblindbrothers.com/',
 'Tyche & Iset Eyewear': 'https://www.tycheandiset.com/',
 'Tyler Ellis': 'https://tylerellis.com/',
 'Un-ti-tled': 'https://www.un-ti-tled.com/',
 'United Legwear & Apparel Co.': 'http://unitedlegwear.com/',
 'Unshattered': 'https://unshattered.org/',
 'Urban Goggles by Lusari': 'https://lusari.com/',
 'V12 Marketing': 'https://v12marketing.com/',
 'Vania & David': 'https://www.vaniaanddavid.com/',
 'Vera Bradley': 'https://www.verabradley.com/us/Home',
 'Veronica Beard': 'https://veronicabeard.com/',
 'Veronique Gabai': 'https://veroniquegabai.com/',
 'VF x Victoire Focx': 'https://victoirefocx.com/VF-24%20catalogue.pdf',
 'Vint & York': 'https://www.vintandyork.com/',
 'Violet & Brooks': 'https://violetandbrooks.com/',
 'VLIV Communications': 'https://vlivcommunications.com/',
 'Volatile, Sbicca, Flojos, Kengos': 'https://www.volatileusa.com/',
 'VSP Vision': 'https://vspglobal.com/',
 'Walters Faith': 'https://waltersfaith.com/',
 'Wear The Future': 'https://wear-thefuture.com/',
 'Wet Knot': 'https://www.wetknotusa.com/',
 'Will Leather Goods': 'https://willleathergoods.com/',
 'With Olivia Grace': 'https://www.witholiviagrace.com/',
 'Wolf and Willa': 'https://www.wolfandwilla.com/',
 'Wolverine': 'https://www.wolverineworldwide.com/',
 'WoolTribe': 'https://wooltribe.co/',
 'WWIN Womenswear In Nevada': 'https://www.wwinshow.com/',
 'WYETH USA': 'https://www.wyethusa.com/',
 'Yenta + Posha': 'https://yentaposha.com/',
 'Zeelum Studios': 'https://zeelum.com/'}

**Comment by nomagick** [comment]
Hi, this was a service disruption we had earlier today. 
Sorry for the incident.

This issue has been fixed and the service is working in normal condition.
