### ISSUE TITLE
Strikethrough text not converted to Markdown

### ISSUE THREAD

**Issue by mquandalle** [jina-ai/reader#120]
When converting a webpage to Markdown, the strikethrough text information is lost:

HTML:
```html
Price: <span style="text-decoration: line-through;">80€</span> 70€
```

Current Markdown output:
```md
Price: 80€ 70€
```

Desired Markdown output:
```md
Price: ~~80€~~ 70€
```

This preserves the strikethrough formatting, which is important for pricing information and content editing. It also ensures correct interpretation by LLMs.

**Comment by nomagick** [comment]
Hi @mquandalle. 
Currently, Reader only works on the HTML tags level.
It does not look into the rendered CSS properties of each element.
To get a strikethrough in markdown, there needs to be a pair of corresponding `<del></del>` tags in the HTML.
This is also the defined behavior of the [strikethrough syntax](https://github.github.com/gfm/#strikethrough-extension-), which is part of GFM.
