### ISSUE TITLE
Walmart how to set a specific zip code

### ISSUE THREAD

**Issue by mukaramkhaleel** [jina-ai/reader#121]
example : 
https://www.walmart.com/ip/Safety-1-Grow-and-Go-Sprint-All-in-One-Convertible-Car-Seat-Camellia-II/264361286?classType=REGULAR
here i want to set zipcode to 60102 how can this be done

**Comment by nomagick** [comment]
Reader does not support setting values on a page.

However I can provide some personal suggestions,
Looks like Walmart is using client IP to determine the address.

My suggestion is to either:
1. Use a proxy server deployed in your local area with a corresponding IP address.
or,
2. Using Cookie of a registered user.
