### ISSUE TITLE
feat: read pdf like arxiv

### ISSUE THREAD

**Issue by yihong0618** [jina-ai/reader#13]
https://arxiv.org/pdf/2403.09060.pdf

**Comment by hanxiao** [comment]
For arxiv pdf, you can use this https://r.jina.ai/https://arxiv.org/html/2403.09060v1

**Comment by yihong0618** [comment]
> For arxiv pdf, you can use this https://r.jina.ai/https://arxiv.org/html/2403.09060v1

thanks
