### ISSUE TITLE
[Feature Request] Multiple target selectors

### ISSUE THREAD

**Issue by MaSchVam** [jina-ai/reader#143]
Some websites present a unique challenge due to their dynamic nature. Sophisticated/advanced ones often have varying classes and elements across different pages with similar URL schemes, and those utilizing A/B testing can further complicate the process. This makes it difficult to consistently access elements using a single target selector. 

Proposal:
I propose adding support for an array of target selectors in Reader. This feature would allow users to input multiple selectors, which Reader would then attempt sequentially. The process would stop and return the desired content as soon as a valid match is found. If none of the selectors are successful, Reader could return a 422 `AssertionFailureError`, maintaining its current behavior.

Not sure how this would play nice with the `X-Wait-For` selector, but it would prevent scenarios where you currently have to fire off a handful of Reader requests until you hit the selector that happened to be there.

**Comment by FreddyAngelo** [comment]
+1 on this 🙌🏻

**Comment by nomagick** [comment]
The current implementation should already support multiple target selectors.

This could be achieved by passing multiple `X-Target-Selector` headers. 
And it will automatically `X-Wait-For` ALL the selectors.

This has a slightly different behavior compared to passing a single selector, but including `,`s inside the selector. Multiple selectors are each being waited for, but a single selector with multiple matches is being waited for as one clause.


Please also note that match all sectors, e.g., `*:not(...)`, are ignored to prevent performance problems.

**Comment by MaSchVam** [comment]
@nomagick Okay, that is great. It sounds like passing multiple `X-Target-Selector` headers would be the best option, if you don't know what the page might look like then - is that correctly understood?

**Comment by nomagick** [comment]
@MaSchVam No in that case please pass a single `x-target-selector` header and use `,`(without spaces) to seperate multiple selects.

If there are multiple `x-target-selector` headers and any one of the selectors doesn't exist on the page, Reader will always wait till the timeout.

**Comment by MaSchVam** [comment]
@nomagick Alright, thanks. Could you clarify, with one header and comma-separated selectors, what is `X-Wait-For` behaviour in that case? 

Is there any workaround if this setup only allows for awaiting a single selector?

**Comment by nomagick** [comment]
@MaSchVam  If you only specify `x-target-selector`, then `x-wait-for-selector` will take the value of your specified `x-target-selector`. You can also specify `x-wait-for-selector` explicitly, then only your specified `x-wait-for-selector` will be waited for.
