### ISSUE TITLE
can not parse image from <picture> tag

### ISSUE THREAD

**Issue by DophinL** [jina-ai/reader#149]
```javascript
fetch('https://r.jina.ai/https://www.cnbc.com/2024/10/29/sam-altmans-reddit-stake-now-worth-over-1-billion-after-earnings-pop.html', {
  method: 'GET',
  headers: {
    "Accept": "application/json",
    "X-With-Images-Summary": "true",
      "X-Target-Selector": ".ArticleBody-articleBody"
  },
})
```

You can see from the execution result that the main image has not been retrieved.

<img width="993" alt="image" src="https://github.com/user-attachments/assets/6d921bca-cc20-498d-a3fc-40e47db57dba">

Please support the <picture> tag. I'm a paid user, thanks 🫡

**Comment by nomagick** [comment]
Thanks for reporting.

I have just updated the service to expose the image in <picture>.

**Comment by DophinL** [comment]
> Thanks for reporting.
> 
> I have just updated the service to expose the image in `<picture>`.
Amazing speed, thank you so much!

**Comment by DophinL** [comment]
@nomagick 
seems not work on this site, didn't get the main picture:
```javascript
fetch('https://r.jina.ai/https://www.foxsports.com/stories/mlb/chris-sale-aaron-judge-shohei-ohtani-highlight-all-mlb-2024-awardees', {
  method: 'GET',
  headers: {
    "Accept": "application/json",
    "X-With-Images-Summary": "true",
      "X-Target-Selector": ".story-content-main"
  },
}).then(res => res.json()).then(res => console.log('jina resp',res))
```

<img width="1095" alt="image" src="https://github.com/user-attachments/assets/7f29c970-03f3-4441-9be4-a91964d8aede">

**Comment by DophinL** [comment]
This website is in the same situation: 

```javascript
fetch('https://r.jina.ai/https://cryptodaily.co.uk/2024/11/crypto-price-analysis-11-14-bitcoin-btc-ethereum-eth-solana-sol-ripple-xrp-dogecoin-doge-uniswap-uni-immutable-imx', {
  method: 'GET',
  headers: {
    "Accept": "application/json",
    "X-With-Images-Summary": "true",
      "X-Target-Selector": ".news-details-layout1"
  },
}).then(res => res.json()).then(res => console.log('jina resp',res))
```

**Comment by nomagick** [comment]
This was because it only has a `srcset` and does not have an `src`.

Now I've modified Reader a bit to consider `srcset`.

**Comment by DophinL** [comment]
> This was because it only has a `srcset` and does not have an `src`.
> 
> Now I've modified Reader a bit to consider `srcset`.

Thanks for the quick response! It seems it hasn't taken effect yet. Has it not been released?

**Comment by nomagick** [comment]
> > This was because it only has a `srcset` and does not have an `src`.
> > Now I've modified Reader a bit to consider `srcset`.
> 
> Thanks for the quick response! It seems it hasn't taken effect yet. Has it not been released?

It had been deployed days ago. 
The image did not show up for this particular page because the [`Readability`](https://github.com/mozilla/readability) lib we use intentionally removed the block while trying to clean up the page.
Try the `markdown` return format to inform Reader not to use `Readability`:

```
curl https://r.jina.ai/https://www.foxsports.com/stories/mlb/chris-sale-aaron-judge-shohei-ohtani-highlight-all-mlb-2024-awardees \
  -H 'x-return-format: markdown' \
  -H 'x-target-selector: .story-content-main'
```
