### ISSUE TITLE
Add parameters to request full text (i.e. don't parse with @mozilla/readability)

### ISSUE THREAD

**Issue by williambarberjr** [jina-ai/reader#28]
Great tool, would love to make more use of this, however, I scrape a lot of home pages of websites and those pages wind up having far too much info removed by readability.js. I'd love to have a parameter I can pass that would allow me to use html-to-text instead. The code to add that is very simple:
```javascript
import { convert } from 'html-to-text';

const options = {
	wordwrap: false,
	selectors: [
		{ selector: 'a', options: { hideLinkHrefIfSameAsText: true, noAnchorUrl: true, ignoreHref: true, linkBrackets: false } },
		{ selector: 'img', format: 'skip' },
		{ selector: 'p', options: { leadingLineBreaks: 1, trailingLineBreaks: 1 } },
		{ selector: 'pre', options: { leadingLineBreaks: 1, trailingLineBreaks: 1 } },
	]
};

text = convert(html, options);
```

That will get you clean text that's well structured from the html though much much longer for home pages like https://www.tanium.com. For that home page, the current reader produces text with: 327 tokens (using the gpt4 tiktoken tokenizer) and html-to-text gives back 2554 tokens. That's far too much information loss for my use case, esp given that much of that information is critical to understanding what the business does.

Finally, while it wouldn't work in js - if you're willing to connect a vision model to interpret images, perhaps you'd consider implementing Trafilatura for articles and similar pages as it slightly outperforms readability.js based on a 2023 analysis from this paper: https://downloads.webis.de/publications/papers/bevendorff_2023b.pdf

Here's one image from the analysis:
<img width="354" alt="image" src="https://github.com/jina-ai/reader/assets/9202147/61f03da6-0bf4-43a5-b86e-c3aa355cb46d">

While adding a parameter like this conflicts a bit with prioritizing the convenience of just dropping the url at the end of https://r.jina.ai/ I think the added info is really critical. It's the difference between me being able to use this for my use case (which I don't think is an extreme edge case) and not being able to use this...

**Comment by williambarberjr** [comment]
I'd also recommend considering adding use of https://metascraper.js.org/#/ for pulling structured data that websites add under the hood (description, keywords, author etc.) for search engines to read/understand what the page is about.

**Comment by hanxiao** [comment]
@nomagick let's look at this

**Comment by williambarberjr** [comment]
Html-to-text has some html-to-markdown related code that never got fully implemented I don't think (https://github.com/html-to-text/node-html-to-text/tree/master/packages/html-to-md). But if you want to retain the markdown format, that may be something worth looking at.

Turndown appears to be a bit more popular and actively maintained, but I wasn't able to get it working with a Cloudflare browser worker for some reason (https://github.com/mixmark-io/turndown) and the demo here: https://mixmark-io.github.io/turndown/ doesn't work all that well for me when I drop in the full html output from client side rendered pages but I'm likely missing a few things as I've only looked at both options briefly.

**Comment by williambarberjr** [comment]
For now though if you could just add an option to return the full html in addition to the markdown text in a json response or similar that would be extremely useful - would allow me and others to get the upside of browser rendering (the primary expense and challenge to scale) with the flexibility to handle dropping the parts of the html we want to drop ourselves. Having the option to return a screenshot might also be useful.
