### ISSUE TITLE
Configure HTTP Proxy

### ISSUE THREAD

**Issue by adrienbrault** [jina-ai/reader#33]
Hey!

How can I configure/use an HTTP Proxy?

For example: https://docs.zyte.com/zyte-api/usage/proxy-mode.html

**Comment by hanxiao** [comment]
can you look at it? @nomagick

**Comment by adrienbrault** [comment]
@nomagick I was thinking I'd have to run it myself to use a proxy ... but `x-proxy-url` is a great idea! 👏 Thank you
