### ISSUE TITLE
Scraping failure (JS): globalrelay.com/company/careers/jobs

### ISSUE THREAD

**Issue by vibl** [jina-ai/reader#34]
Jina Reader does not extract the job postings from this website:
https://r.jina.ai/https://www.globalrelay.com/company/careers/jobs/?gh_jid=5117891004

**Comment by vibl** [comment]
Never mind. I found a way to scrape it.

**Comment by cybors** [comment]
> Never mind. I found a way to scrape it.

How did you achieve this? I have encountered the same problem.
