### ISSUE TITLE
Please advise on how to filter out unwanted content

### ISSUE THREAD

**Issue by chenqianhe** [jina-ai/reader#45]
I studied the source code as a whole and found that I mainly use turndown to convert html into Markdown. 

What puzzles me is that the things returned by your interface are very clean and do not contain some useless information on the page. I am very curious about how you do it. Specifically, for example, the navigation bar and comment area of some pages will not appear in the content returned by your interface.

I would like to ask you what kind of processing you have done? Or is there some source code that I haven't seen?

**Comment by hanxiao** [comment]
The cleaning part is done by `mozilla/readability`. Sometime it overdoes, filtering out too much information, and you can set request header to control the levels of details. [Please read this section](https://github.com/jina-ai/reader?tab=readme-ov-file#using-request-headers)

**Comment by chenqianhe** [comment]
> The cleaning part is done by `mozilla/readability`. Sometime it overdoes, filtering out too much information, and you can set request header to control the levels of details. [Please read this section](https://github.com/jina-ai/reader?tab=readme-ov-file#using-request-headers)

Thank you very much for your reply. Let me take a look at the guidance you provided and delve deeper into it
