### ISSUE TITLE
How to get the Available tokens though Reader API to monitor the token usage?

### ISSUE THREAD

**Issue by songkq** [jina-ai/reader#64]
@nomagick @hanxiao @zac-li @saahil @CatStark Hi all, could you please give some advice for how to get the available tokens through the Reader API instead of the "'Buy tokens' tab" shown in https://jina.ai/reader/?
![image](https://github.com/jina-ai/reader/assets/30183023/27a70304-52bb-40a5-ab7d-8ce2bf6192d1)
![image](https://github.com/jina-ai/reader/assets/30183023/aaea620d-13c2-43f2-a3e7-2bb6760f468a)

**Comment by hanxiao** [comment]
@songkq if u want to check via UI, u can also type in your key and it will show.


![image](https://github.com/jina-ai/reader/assets/2041322/21a533c9-080c-400c-b15c-54896cac2130)

**Comment by songkq** [comment]
@hanxiao @nomagick Thanks.  Could you please add a JSON response format for "[Balance left] 992083", e.g., {'available_tokens': 1000000}?

**Comment by songkq** [comment]
@hanxiao @nomagick Another issue please... Even after I add a freetrial API_Key during request, it seems that I cannot parse more than 20 urls in asynchronism and concurrency during one minute.  It returns the response `"Whoa there, turbo! You've hit the rate limit on the Reader API. Cool down a bit and try again later; or resend the request with a Jina AI API Key in the authorization header...."`

![image](https://github.com/jina-ai/reader/assets/30183023/15a8c244-d148-43ff-bc40-961ffb9b6d5b)

Could you please give some advice for this issue?

**Comment by hanxiao** [comment]
Regarding the 20 RPM with API key issue u have, I have a feeling your header may be wrongly set and not respected by the server, could it be a misspelling or something?

Here is a google colab that you can refer to https://colab.research.google.com/drive/1uoBy6_7BhxqpFQ45vuhgDDDGwstaCt4P#scrollTo=MTEWpqyxCJ5U
