### ISSUE TITLE
The open source is trash. The most important parts are not open sourced. The open sourced portion doesn't even run.

### ISSUE THREAD

**Issue by dashi6174** [jina-ai/reader#69]
The open source is trash. The most important parts are not open sourced. The open sourced portion doesn't even run.
---
垃圾开源，最重要的部分不开源。开源的跑不起来

**Comment by dashi6174** [comment]
垃圾开源，最重要的部分不开源。开源的跑不起来

**Comment by yaoye7758521** [comment]
- you are right,hehehe
