### ISSUE TITLE
BUG: Incorrectly reading SVG "title" elements as HTML "title" elements (repro & proposed solution)

### ISSUE THREAD

**Issue by dallashall** [jina-ai/reader#71]
## Description of Bug
When creating markdown for crawled pages, `<title>` elements inside of `<svg>` elements are being treated as if they were HTML title elements.

### Steps to reproduce bug
1. Visit a webpage with an SVG (one or more) that contains an SVG `title` element
    ```
    curl https://r.jina.ai/https://www.smashingmagazine.com/2021/05/accessible-svg-patterns-comparison/ \
	    -H "X-Return-Format: markdown" \
	    -H "X-Target-Selector: svg"
    ```
2. See that the output contains the SVG title (which is most often provided as an accessibility helper for images, and should not be treated the same as an HTML title)
    ```
    Clear Search
    ===============% 
    ```

### Root Cause

I believe the issue comes from [this part](https://github.com/jina-ai/reader/blob/main/backend/functions/src/cloud-functions/crawler.ts#L125) of the crawler. It uses a simple filter on element type (looking for `type`).

### Possible solutions:
- Only treat the `<title>` as an h1 if its parent element is `<head>`
- Ignore the element if `ownerSVGElement` is present
- Differentiate based on node name (`title` for SVG titles and `TITLE` for html, but I am not sure how consistent that is)

#### More information:
- [SVG title](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title) (MDN)

---

I'm happy to make a pull request with one of these fixes, but I do not have a working local version, so I will be unable to test any solution I propose.

**Comment by nomagick** [comment]
Hi, thanks for reporting.
I've made a change to truncate SVG from the HTML [here](https://github.com/jina-ai/reader/commit/154d8ede459cc06dfb54a7e26664d4b90f0394ff).
I hope this fixes your case.

**Comment by dallashall** [comment]
@nomagick Thank you for the quick response! That appears to have fixed my use cases.
