### ISSUE TITLE
百度百科的数据，仅仅提取到了网盟广告，核心的内容没有提取。

### ISSUE THREAD

**Issue by fu1996** [jina-ai/reader#75]
复现url:[https://r.jina.ai/https://baike.baidu.com/item/%E9%BC%BB%E7%82%8E/190075](https://r.jina.ai/https://baike.baidu.com/item/%E9%BC%BB%E7%82%8E/190075)
![img_v3_02bo_2f59192b-31c6-4ced-8e3c-387b25e819fg](https://github.com/jina-ai/reader/assets/42232973/da5efcee-1825-4731-bc19-8e6bdcd36cef)

**Comment by nomagick** [comment]
哈哈，那也算获取到本体了

单独指定一下要获取的元素吧：

```bash
curl https://r.jina.ai/https://baike.baidu.com/item/%E9%BC%BB%E7%82%8E/190075 -H 'x-target-selector: div[type="defaultTab"]'
```
