### ISSUE TITLE
SecurityCompromiseError

### ISSUE THREAD

**Issue by bubble-xu** [jina-ai/reader#87]
{"data":null,"code":451,"name":"SecurityCompromiseError","status":45102,"message":"Domain mp.weixin.qq.com blocked until Fri Jul 05 2024 06:48:50 GMT+0000 (Coordinated Universal Time) due to previous abuse found on http://mp.weixin.qq.com/s?__biz=MzIwMzU4ODE5NQ==&mid=2247719218&idx=1&sn=208b06ad8d78cd329b2db70b94724def&chksm=96c0ce3ea1b747288ae91e8c3b3805384ab8c1e1bf76c8dc1e5217d71e5839da41e34020f71f: DoS attack suspected: DOM tree too deep","readableMessage":"SecurityCompromiseError: Domain mp.weixin.qq.com blocked until Fri Jul 05 2024 06:48:50 GMT+0000 (Coordinated Universal Time) due to previous abuse found on http://mp.weixin.qq.com/s?__biz=MzIwMzU4ODE5NQ==&mid=2247719218&idx=1&sn=208b06ad8d78cd329b2db70b94724def&chksm=96c0ce3ea1b747288ae91e8c3b3805384ab8c1e1bf76c8dc1e5217d71e5839da41e34020f71f: DoS attack suspected: DOM tree too deep"}

**Comment by nomagick** [comment]
Indeed. 
As it suggests, this host contained some suspicious content and was blocked for a while to protect our service.

Despite this blockade, you can always use an API key to authenticate yourself.
Authenticated users are not affected by these blockades.

**Comment by zvictor** [comment]
> Despite this blockade, you can always use an API key to authenticate yourself.
Authenticated users are not affected by these blockades.

This is good to know! I was trying to use proxies to bypass this issue thinking that the blockage was happening on the host side, not on the middleman (Jina).

Writing a Error Codes page would be very helpful!
