### ISSUE TITLE
Pdf parsing

### ISSUE THREAD

**Issue by kulich-d** [jina-ai/reader#89]
I want to parse my PDF file using your API or code, but I can't find any instructions. Could you please share some guidance?

**Comment by nomagick** [comment]
Reader can only parse PDFs that have a publicly accessible URL.

If your PDF files does not have such a URL, you'll need to first get one for each of your files.

You may:

- Upload your PDF files to an S3-like service that can provide URLs for your files.
- Locally run a web server like Nginx, then use a service like ngrok to expose your files to the Internet temporarily.
