### ISSUE TITLE
Jina Search with subdomains

### ISSUE THREAD

**Issue by PriNova** [jina-ai/reader#91]
When I try to search for a specific topic on a subdomain it won't work as expected.

For example, I searched for the usage of geometry nodes in the Blender documentation at docs.blender.com, but the results are from the entire web.

For that I used the newly introduced `site` headers argument.

It would be nice to have the ability search under subdomains too.

**Comment by nomagick** [comment]
Hi.
Previously there was an issue with the site parameter.
Now you can do it by adding `?site=example.com` query parameters.

Fixed in 786b1828b7dff4c702081b8cd0305c1e632065b1

**Comment by PriNova** [comment]
> Hi. Previously there was an issue with the site parameter. Now you can do it by adding `?site=example.com` query parameters.
> 
> Fixed in [786b182](https://github.com/jina-ai/reader/commit/786b1828b7dff4c702081b8cd0305c1e632065b1)

Thank you for the hint.
My initial question is, does this work also with subdomain URLs like `docs.blender.org` as the `site:` header with the API?

**Comment by nomagick** [comment]
My observation is yes.
We are using Brave Search API, you can try for yourself on https://search.brave.com/.
Specifying `site:` after the search term.

**Comment by PriNova** [comment]
It works as expected @nomagick 
Thank you for your effort and explanation.
