### ISSUE TITLE
Randomly Not Getting Content - Using Paid API

### ISSUE THREAD

**Issue by Meathelix1** [jina-ai/reader#94]
I have been using the API for a little while now and on a certain site it will be a random when it comes to gathering the content. 

Sometimes it will give me full content, sometimes it will give me the first 10 words and that is it. 
I have tried all the settings that claims to fix this issue however it does not for this site.

Not sure who to contact when it comes to this issue with the paid API.

UPDATED: I just decided to create a function that will detect if it did not scrape correctly and retry. It will cost a bit more but for now it works.

**Comment by MaSchVam** [comment]
@Meathelix1 Having the same issue. Are you waiting in-between retries - and if so, for how long?

I always expect more than 150 words, and I retry 3 times, but I don’t wait currently. Sometimes this works, sometimes it doesen’t - so it seems to me, that waiting may be key.
