### ISSUE TITLE
How do I use the x-proxy-url header

### ISSUE THREAD

**Issue by jackli0127** [jina-ai/reader#95]
I specify our forward proxy server via the x-proxy-url header with the command below. However, I can't see the request reaching our proxy server at x.x.x.x. Is there something I misunderstand?

curl --location 'https://r.jina.ai/https://github.com' --header 'x-proxy-url: x.x.x.x:xx'

**Comment by nomagick** [comment]
You need to specify a real URL including the protocol of your proxy.
For example `http://x.x.x.x:xx` or `socks5://x.x.x.x:xx`

**Comment by jackli0127** [comment]
It works. Thank you!
