### ISSUE TITLE
@nomagick 我这边基于当前代码库的部分核心逻辑实现了一个简单的server 服务的代码库，不知道贵司是否介意我这边开源一下基于当前这个代码库的核心业务逻辑创建的库呢？

### ISSUE THREAD

**Issue by AmbroseX** [jina-ai/reader#96]
@nomagick 我这边基于当前代码库的部分核心逻辑实现了一个简单的server 服务的代码库，不知道贵司是否介意我这边开源一下基于当前这个代码库的核心业务逻辑创建的库呢？

_Originally posted by @fu1996 in https://github.com/jina-ai/reader/issues/82#issuecomment-2191480282_
            

基于这个开源的修改再开源符合开源协议

**Comment by nomagick** [comment]
是的基于这个库二次开发是没有问题的
